### ISSUE TITLE
Does this need a video series?

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#368]

**Comment by tomByrer** [comment]
Still could use more videos (smaller & practical examples) & better docs IMHO.

Good start for machine ideas: https://xstate-catalogue.com/

**Comment by StoneCypher** [comment]
Yeah, you're not wrong

It's really hard to find the time but [I have some planned now](https://github.com/StoneCypher/fsl/issues?q=is%3Aissue+is%3Aopen+video)

I do kind of like the idea of the catalogue.  I should probably do that.  Maybe, uh, with comparisons to other machines, to emphasize the value of the DSL

I moved to the issue tracker on the [fsl repo](https://github.com/StoneCypher/fsl/issues) when I found out NPM docked in search you for having open issues
