### ISSUE TITLE
NodeJS approach to producing SVGs

### ISSUE THREAD

**Issue by sunwukonga** [StoneCypher/jssm#377]
**So what's the feature?**
Some documented way to produce SVGs from state machines in Node. 

**Is this related to a problem?  If so, what?**
The jssm-vis-demo, while good at quickly visualizing and getting started, is not useful for more serious work. Closing the browser windows destroys all progress.
**Describe the solution you'd like**
Currently, I've pulled the `dot` function out of `src/ts/jssm-viz.ts` in ` https://github.com/StoneCypher/jssm-viz/`, and imported that function into my project for generating SVGs. I saved the code as js, removing the few ts type references.
I then used `spawn` imported from `child_process` to run GraphViz' `dot` executable on the .dot file I produce to get an svg. 
**Describe alternatives you've considered**
I tried using jssm-viz, but it died without error messages in Node.
**Additional context as you see fit**

**Comment by StoneCypher** [comment]
the mechanism is [dot_to_string](https://github.com/StoneCypher/jssm-viz/blob/master/src/ts/jssm-viz.ts#L95) in jssm-viz

you can see it in use in [graph explorer](https://stonecypher.github.io/jssm-viz-demo/graph_explorer.html) in the `svg` button on the top edge of the editor window

i'm sorry it took me so long to notice these, @sunwukonga

**Comment by StoneCypher** [comment]
i haven't actually tried this in node actually

`svg_el` would need a dom (which you could supplement with `jsdom`) but `svg_el` shouldn't

i believe that should Just Work &trade;

I'll try to get a tutorial together on this this weekend (no promises)

**Comment by StoneCypher** [comment]
hm

it looks like i actually took a stab at this a year ago

at the moment node's just up and dying when you load the bundle

that said the author expects this to work in node, and has examples.  i'll see if i can figure out what the difference is

https://github.com/mdaines/viz.js/issues/161

**Comment by StoneCypher** [comment]
This is now implemented in `jssm-viz` and the `cli` is mostly done

The `github action` is also mostly done

**Comment by StoneCypher** [comment]
Okay.

It's not really ready for prime time, but, there is now a `cli` that can consume `fsl` and produce `svg` on disk.

It only produces them in the same location as the source right now (there's a bunch of command line options to change that but they're not honored yet)

It doesn't do any of the other image formats yet

[But it does work](https://github.com/StoneCypher/jssm-viz-cli)

**Comment by StoneCypher** [comment]
I just realized you want the SVG in your app, not as a CLI

That's also implemented in there

```js
const svg_code = await fsl_to_svg_string(fsl_code);
```

I need to document this but I'm closing the issue because I believe it to be complete

If that's not correct, please re-open it and/or tag me

**Comment by StoneCypher** [comment]
Actually, there's a live instance of `jssm-viz` bound to `window` on [graph explorer](https://stonecypher.github.io/jssm-viz-demo/graph_explorer.html), so you can just open a developer console and try it there

```
const viz = window.jssm_viz;
const viz.fsl_to_svg_string('this => is -> an ~> example;');
```

![image](https://user-images.githubusercontent.com/77482/73145146-b111e700-4060-11ea-9bc0-74b6779e8269.png)

works in node too

![image](https://user-images.githubusercontent.com/77482/73145180-ecacb100-4060-11ea-93d4-d88e7b7040f1.png)
