### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by tomeraz** [StoneCypher/jssm#389]
Hi,

I really like the syntax and visualization. I want to use jssm in a web project.
Is there a way to execute event handlers when a certain state or transition are called?
Thanks!

**Comment by StoneCypher** [comment]
I haven't implemented hooks yet.  They're on the list of things I need to get done

Since the library is synchronous, you could do something like

```javascript
function die() { ... }
function next_level() { ... }

const active_nodes = {
  trap_bedroom: die,
  treasure: next_level,
  snake_bedroom: die
};

const level_machine = sm`
  initial_state: porch;
  porch => front_door => hallway => stairs => 2fl_hallway;
  2fl_hallway -> [treasure_bedroom, snake_bedroom, trap_bedroom, boring_bedroom];
`;

function transition_hooked(machine, node_to) {
  machine.transition(node_to);
  if (Object.keys(active_nodes).includes(machine.state())) {
    active_nodes[machine.state()]();
  }
}
```

then it's just

```javascript
transition_hooked(level_machine, 'front_door');
transition_hooked(level_machine, 'hallway');
transition_hooked(level_machine, 'stairs');
transition_hooked(level_machine, '2fl_hallway');
transition_hooked(level_machine, 'treasure_bedroom');
```

which is kinda gross, but it should be enough until i get my shit together

**Comment by StoneCypher** [comment]
please let me know if this temporary solution covers you, and i'll come back with a real answer when it's there

**Comment by tomeraz** [comment]
I will go with another (dead) fsm lib and move to jssm when I can. Thank you for your spectacular work 🙏

**Comment by StoneCypher** [comment]
bummer.  over hooks?

**Comment by tomeraz** [comment]
Hooks are important to me. No time to code this myself in my pre-seed
startup. Following jssm releases. Thanks 🙏

**Comment by StoneCypher** [comment]
Decided to circle back around and make sure people who had spoken up had seen

There is a hooking notation now.  You can use it fluently or standalone.

```javascript
const traffic_light = sm`Red => Green => Yellow => Red`
  .hook('Yellow', 'Red', () => console.log('RED LIGHT') );
```

There are also other hook notations for hooking actions, entry, exit, and so forth, now.
