### ISSUE TITLE
Problem defining more than one action with the same transition path

### ISSUE THREAD

**Issue by xtovski** [StoneCypher/jssm#515]
I am trying to define two distinct actions that have the same transition path. Example:
```
State_A 'action_a' -> State_B;
State_A 'action_b' -> State_B;
```
I get an error like this:
`JssmError: already has "State_A" to "State_B"`
But it makes sense to have to different actions (as they may have two distinct state transition meaning) that define transition conditions.

**Comment by StoneCypher** [comment]
Anyway as it stands right now, FSL disallows multiple edges between two states.  The easiest workaround is to have a landing state to catch them and to carry on from there.

I'll prioritize automatic successor states so that this won't impact you much

**Comment by xtovski** [comment]
Yeah, to make it more semantic, I've implemented 'auto' action, so that SM factory will automatically process it and move to the next state.
Like so:
```
a 'do' -> b;
a 'dotoo' -> c 'auto' -> b;
```

Or even so:
```
a 'do' -> a;
a 'dotoo' -> b 'auto' -> a;
```

But again, I guess having multiple actions would make code much more clean.

**Comment by StoneCypher** [comment]
I agree that this is a desirable thing

The reason I'm dragging my heels is that a huge portion of the codebase is written with the assumption that you can ask the machine for the edge between `a` and `b`, and get an unambiguous answer

To do this would break that, which is a massive breaking change and also would mean a whole bunch of stuff would need to move to being container based, which would probably slow things down by an order of ten

I have kicked around the idea of saying "it'll return the main path and only main path has this restriction" but that still breaks older machines written without main paths

I'm still thinking over what I think is the right thing to do here

Would you be okay with my closing this, and talking on StoneCypher/fsl#325 instead, please?  There are ~30 repos and it's hard to keep track of things if they're not all in the same place

**Comment by StoneCypher** [comment]
closing here because you're chatting there
