### ISSUE TITLE
Non-deterministic finite state automatons?

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#65]
Sup @Patater

**Comment by StoneCypher** [comment]
nah

**Comment by Patater** [comment]
K

**Comment by StoneCypher** [comment]
i mean i looked at it for a long time but the truth is i don't actually understand it or the value proposition very well

it's hard to find material that says "this is what you get out of this"

i'm open to persuasion

**Comment by StoneCypher** [comment]
@Patater wait, is an NDA just a FSM whose transitions can be from a random list?

**Comment by StoneCypher** [comment]
i may actually already do these
